#!/bin/env zsh

# export default env
export EDITOR="code --new-window"

# setup nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(starship init zsh)"

# set prompt to current directory
if [ $ITERM_SESSION_ID ]; then
precmd() {
  echo -ne "\033]0;${PWD##*/}\007"
}
fi


# export path
# export PATH="$HOME/.tools:$HOME/bin:$HOME/.bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/bin:$PATH"
# export PATH="$PATH:$HOME/Library/Python/2.7/bin"
# export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
# export PATH="$PATH:$HOME/.dotnet:$HOME/.dotnet/tools"

fpath=(~/.zsh/functions $fpath)

autoload -U ~/.zsh/functions/*(:t)

HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
REPORTTIME=10 # print elapsed time when more than 10 seconds

setopt NO_BG_NICE # don't nice background tasks
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS # allow functions to have local options
setopt LOCAL_TRAPS # allow functions to have local traps
setopt HIST_VERIFY
setopt SHARE_HISTORY # share history between sessions ???
setopt EXTENDED_HISTORY # add timestamps to history
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
setopt IGNORE_EOF

setopt APPEND_HISTORY # adds history
setopt INC_APPEND_HISTORY SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS

zle -N newtab

bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[[5D' beginning-of-line
bindkey '^[[5C' end-of-line
bindkey '^[[3~' delete-char
bindkey '^[^N' newtab
bindkey '^?' backward-delete-char 
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

cat << "EOF"
                     .mmMMMMMMMMMMMMMmm.                              
                 .mMMMMMMMMMMMMMMMMMMMMMMMm.                          
              .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm.                       
            .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                     
          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                   
         MMMMMMMM'  `"MMMMM"""""""MMMM""`  'MMMMMMMM                  
        MMMMMMMMM                           MMMMMMMMM                 
       MMMMMMMMMM:                         :MMMMMMMMMM                
      .MMMMMMMMMM                           MMMMMMMMMM.               
      MMMMMMMMM"                             "MMMMMMMMM               
      MMMMMMMMM          Welcome back,        MMMMMMMMM               
      MMMMMMMMM            @ethanis           MMMMMMMMM               
      MMMMMMMMMM                             MMMMMMMMMM               
      `MMMMMMMMMM                           MMMMMMMMMM`               
       MMMMMMMMMMMM.                     .MMMMMMMMMMMM                
        MMMMMM  MMMMMMMMMM         MMMMMMMMMMMMMMMMMM                 
         MMMMMM  'MMMMMMM           MMMMMMMMMMMMMMMM                  
          `MMMMMM  "MMMMM           MMMMMMMMMMMMMM`                   
            `MMMMMm                 MMMMMMMMMMMM`                     
              `"MMMMMMMMM           MMMMMMMMM"`                       
                 `"MMMMMM           MMMMMM"`                          
                     `""M           M""`                              
EOF